
# Configure checks

INCLUDE( CheckIncludeFile )
INCLUDE( CheckIncludeFiles )
INCLUDE( CheckFunctionExists )
INCLUDE( CheckSymbolExists )
INCLUDE( CheckTypeSize ) 
INCLUDE( CheckCSourceCompiles )
INCLUDE( FindThreads )


# Ignoring the following tests because I don't 
# have an answer or they are obsolete
# SET( AC_APPLE_UNIVERSAL_BUILD ) 
# SET( BUILD_MODULES )
# SET( CIPHER_SUPPORT )
# SET( CLOSEDIR_VOID )
# SET(  )
# SET(  )
# SET(  )

# SET( CIPHER_SUPPORT TRUE )
# SET( MAGICKCORE_PACKAGE_NAME \"ImageMagick\" )
IF( MSVC )
	SET( inline __inline )
	SET( __func__ __FUNCTION__ )
ENDIF( MSVC )

# Maually setting
# Possible RETSIGTYPE test
#include <sys/types.h>
#include <signal.h>
#ifdef signal
# undef signal
#endif
#ifdef __cplusplus
#extern "C" void (*signal (int, void (*)(int)))(int);
#else
#void (*signal ()) ();
#endif

#int
#main ()
#{
#  return 0;
#}

SET( RETSIGTYPE void )
SET( SELECT_TYPE_ARG1 int )
SET( SELECT_TYPE_ARG234 "(fd_set *)" )
SET( SELECT_TYPE_ARG5 "(struct timeval *)" )

SET( CMAKE_REQUIRED_INCLUDES ${CMAKE_INCLUDE_PATH} )
#SET( CMAKE_REQUIRED_LIBRARIES
CHECK_FUNCTION_EXISTS( argz_add HAVE_ARGZ_ADD )
CHECK_FUNCTION_EXISTS( argz_append HAVE_ARGZ_APPEND )
CHECK_FUNCTION_EXISTS( argz_count HAVE_ARGZ_COUNT )
CHECK_FUNCTION_EXISTS( argz_create_sep HAVE_ARGZ_CREATE_SEP )
CHECK_FUNCTION_EXISTS( argz_insert HAVE_ARGZ_INSERT )
CHECK_FUNCTION_EXISTS( argz_next HAVE_ARGZ_NEXT )
CHECK_FUNCTION_EXISTS( argz_stringify HAVE_ARGZ_STRINGIFY )
CHECK_INCLUDE_FILE( argz.h HAVE_ARGZ_H )

CHECK_INCLUDE_FILE( arm/limits.h HAVE_ARM_LIMITS_H )
CHECK_INCLUDE_FILE( CL/opencl.h HAVE_CL_OPENCL_H )
CHECK_INCLUDE_FILE( complex.h HAVE_COMPLEX_H )
CHECK_INCLUDE_FILE( dld.h HAVE_DLD_H )
CHECK_INCLUDE_FILE( dlfcn.h HAVE_DLFCN_H )
CHECK_INCLUDE_FILE( dl.h HAVE_DL_H )
CHECK_INCLUDE_FILE( errno.h HAVE_ERRNO_H )
CHECK_INCLUDE_FILE( fcntl.h HAVE_FCNTL_H )
CHECK_INCLUDE_FILE( ft2build.h HAVE_FT2BUILD_H )
CHECK_INCLUDE_FILE( inttypes.h HAVE_INTTYPES_H )
CHECK_INCLUDE_FILE( limits.h HAVE_LIMITS_H )
CHECK_INCLUDE_FILE( linux/unistd.h HAVE_LINUX_UNISTD_H )
CHECK_INCLUDE_FILE( locale.h HAVE_LOCALE_H )
CHECK_INCLUDE_FILE( machine/param.h HAVE_MACHINE_PARAM_H )
CHECK_INCLUDE_FILE( mach-o/dyld.h HAVE_MACH_O_DYLD_H )
CHECK_INCLUDE_FILE( memory.h HAVE_MEMORY_H )
CHECK_INCLUDE_FILE( process.h HAVE_PROCESS_H )
CHECK_INCLUDE_FILE( OpenCL/OpenCL.h HAVE_OPENCL_OPENCL_H )
CHECK_INCLUDE_FILE( OS.h HAVE_OS_H )
CHECK_INCLUDE_FILE( stdarg.h HAVE_STDARG_H )
CHECK_INCLUDE_FILE( stdbool.h HAVE_STDBOOL_H )
CHECK_INCLUDE_FILE( stddef.h HAVE_STDDEF_H )
CHECK_INCLUDE_FILE( stdint.h HAVE_STDINT_H )
CHECK_INCLUDE_FILE( stdlib.h HAVE_STDLIB_H )
CHECK_INCLUDE_FILE( strings.h HAVE_STRINGS_H )
CHECK_INCLUDE_FILE( string.h HAVE_STRING_H )
CHECK_INCLUDE_FILE( sys/dl.h HAVE_SYS_DL_H )
CHECK_INCLUDE_FILE( sys/ipc.h HAVE_SYS_IPC_H )
CHECK_INCLUDE_FILE( sys/param.h HAVE_SYS_PARAM_H )
CHECK_INCLUDE_FILE( sys/resource.h HAVE_SYS_RESOURCE_H )
CHECK_INCLUDE_FILE( sys/select.h HAVE_SYS_SELECT_H )
CHECK_INCLUDE_FILE( sys/socket.h HAVE_SYS_SOCKET_H )
CHECK_INCLUDE_FILE( sys/stat.h HAVE_SYS_STAT_H )
CHECK_INCLUDE_FILE( sys/syslimits.h HAVE_SYS_SYSLIMITS_H )
CHECK_INCLUDE_FILE( sys/timeb.h HAVE_SYS_TIMEB_H )
CHECK_INCLUDE_FILE( sys/times.h HAVE_SYS_TIMES_H )
CHECK_INCLUDE_FILE( sys/time.h HAVE_SYS_TIME_H )
CHECK_INCLUDE_FILE( sys/types.h HAVE_SYS_TYPES_H )
CHECK_INCLUDE_FILE( sys/wait.h HAVE_SYS_WAIT_H )
CHECK_INCLUDE_FILE( tiffconf.h HAVE_TIFFCONF_H )
CHECK_INCLUDE_FILE( tiffio.h HAVE_TIFFIO_H )
IF( IMAGEMAGICK_WITH_TIFF AND HAVE_TIFFIO_H )
	#SET( CMAKE_REQUIRED_INCLUDES tiffio.h )
	SET( CMAKE_REQUIRED_LIBRARIES tiff )
	CHECK_FUNCTION_EXISTS( TIFFIsCODECConfigured HAVE_TIFFISCODECCONFIGURED )
	CHECK_FUNCTION_EXISTS( TIFFMergeFieldInfo HAVE_TIFFMERGEFIELDINFO )
	CHECK_FUNCTION_EXISTS( TIFFReadEXIFDirectory HAVE_TIFFREADEXIFDIRECTORY )
	CHECK_FUNCTION_EXISTS( TIFFSetErrorHandlerExt HAVE_TIFFSETERRORHANDLEREXT )
	CHECK_FUNCTION_EXISTS( TIFFSetTagExtender HAVE_TIFFSETTAGEXTENDER )
	CHECK_FUNCTION_EXISTS( TIFFSetWarningHandlerExt HAVE_TIFFSETWARNINGHANDLEREXT )
	CHECK_FUNCTION_EXISTS( TIFFSwabArrayOfTriples HAVE_TIFFSWABARRAYOFTRIPLES )
	SET( CMAKE_REQUIRED_INCLUDES )
	#SET( CMAKE_REQUIRED_LIBRARIES )
ENDIF( IMAGEMAGICK_WITH_TIFF AND HAVE_TIFFIO_H )

CHECK_INCLUDE_FILE( unistd.h HAVE_UNISTD_H )
CHECK_INCLUDE_FILE( wchar.h HAVE_WCHAR_H )
CHECK_INCLUDE_FILE( windows.h HAVE_WINDOWS_H )
CHECK_INCLUDE_FILE( lcms.h HAVE_LCMS_H )
CHECK_INCLUDE_FILE( lcms/lcms.h HAVE_LCMS_LCMS_H )

#SET (CMAKE_EXTRA_INCLUDE_FILES
#  sys/types.h
#  stdint.h
#  inttypes.h
#  sys/time.h
#  sys/uuid.h
#  sys/event.h
#  sys/utime.h
#  sys/endian.h
#  ucontext.h
#  utime.h
#  uuid.h
#  aio.h
#  guiddef.h
#  stddef.h
#)
#SET( CMAKE_REQUIRED_INCLUDES math.h )
if (NOT MSVC)
    SET( CMAKE_REQUIRED_LIBRARIES m )
endif ()

CHECK_FUNCTION_EXISTS( atexit HAVE_ATEXIT )
CHECK_FUNCTION_EXISTS( clock HAVE_CLOCK )
CHECK_FUNCTION_EXISTS( closedir HAVE_CLOSEDIR )
CHECK_SYMBOL_EXISTS( cygwin_conv_path sys/cygwin.h HAVE_DECL_CYGWIN_CONV_PATH )
CHECK_FUNCTION_EXISTS( directio HAVE_DIRECTIO )
CHECK_FUNCTION_EXISTS( _dyld_func_lookup HAVE_DYLD )
CHECK_FUNCTION_EXISTS( dlerror HAVE_DLERROR )
CHECK_FUNCTION_EXISTS( execvp HAVE_EXECVP )
CHECK_FUNCTION_EXISTS( floor HAVE_FLOOR )
CHECK_FUNCTION_EXISTS( fork HAVE_FORK )
IF( HAVE_FORK )
	SET( HAVE_WORKING_FORK 1 )
ENDIF( HAVE_FORK )
CHECK_FUNCTION_EXISTS( ftime HAVE_FTIME )
CHECK_FUNCTION_EXISTS( ftruncate HAVE_FTRUNCATE )
CHECK_FUNCTION_EXISTS( getcwd HAVE_GETCWD )
CHECK_FUNCTION_EXISTS( getdtablesize HAVE_GETDTABLESIZE )
CHECK_FUNCTION_EXISTS( getexecname HAVE_GETEXECNAME )
CHECK_FUNCTION_EXISTS( getpagesize HAVE_GETPAGESIZE )
CHECK_FUNCTION_EXISTS( getpid HAVE_GETPID )
CHECK_FUNCTION_EXISTS( getrlimit HAVE_GETRLIMIT )
CHECK_FUNCTION_EXISTS( getrusage HAVE_GETRUSAGE )
CHECK_FUNCTION_EXISTS( gettimeofday HAVE_GETTIMEOFDAY )
CHECK_FUNCTION_EXISTS( gmtime_r HAVE_GMTIME_R )
CHECK_FUNCTION_EXISTS( j0 HAVE_J0 )
CHECK_FUNCTION_EXISTS( j1 HAVE_J1 )
CHECK_FUNCTION_EXISTS( localtime_r HAVE_LOCALTIME_R )
CHECK_FUNCTION_EXISTS( lstat HAVE_LSTAT )
CHECK_FUNCTION_EXISTS( memmove HAVE_MEMMOVE )
CHECK_FUNCTION_EXISTS( memset HAVE_MEMSET )
CHECK_FUNCTION_EXISTS( mkstemp HAVE_MKSTEMP )
CHECK_FUNCTION_EXISTS( munmap HAVE_MUNMAP )
CHECK_FUNCTION_EXISTS( opendir HAVE_OPENDIR )
CHECK_FUNCTION_EXISTS( pclose HAVE_PCLOSE )
CHECK_FUNCTION_EXISTS( poll HAVE_POLL )
CHECK_FUNCTION_EXISTS( popen HAVE_POPEN )
CHECK_FUNCTION_EXISTS( posix_fadvise HAVE_POSIX_FADVISE )
CHECK_FUNCTION_EXISTS( posix_fallocate HAVE_POSIX_FALLOCATE )
CHECK_FUNCTION_EXISTS( posix_madvise HAVE_POSIX_MADVISE )
CHECK_FUNCTION_EXISTS( posix_memalign HAVE_POSIX_MEMALIGN )
CHECK_FUNCTION_EXISTS( pow HAVE_POW )
CHECK_SYMBOL_EXISTS( pread "" HAVE_DECL_PREAD )
CHECK_FUNCTION_EXISTS( pread HAVE_PREAD )
#SET( HAVE_DECL_PREAD ${HAVE_PREAD} )
CHECK_SYMBOL_EXISTS( pwrite unistd.h HAVE_DECL_PWRITE )
CHECK_FUNCTION_EXISTS( pwrite HAVE_PWRITE )
#SET( HAVE_DECL_PWRITE ${HAVE_PWRITE} )
CHECK_FUNCTION_EXISTS( raise HAVE_RAISE )
CHECK_FUNCTION_EXISTS( rand_r HAVE_RAND_R )
CHECK_FUNCTION_EXISTS( readdir HAVE_READDIR )
CHECK_FUNCTION_EXISTS( readdir_r HAVE_READDIR_R )
CHECK_FUNCTION_EXISTS( readlink HAVE_READLINK )
CHECK_FUNCTION_EXISTS( realpath HAVE_REALPATH )
CHECK_FUNCTION_EXISTS( seekdir HAVE_SEEKDIR )
CHECK_FUNCTION_EXISTS( select HAVE_SELECT )
CHECK_FUNCTION_EXISTS( setlocale HAVE_SETLOCALE )
CHECK_FUNCTION_EXISTS( setvbuf HAVE_SETVBUF )
CHECK_FUNCTION_EXISTS( sigaction HAVE_SIGACTION )
CHECK_FUNCTION_EXISTS( sigemptyset HAVE_SIGEMPTYSET )
CHECK_FUNCTION_EXISTS( spawnvp HAVE_SPAWNVP )
CHECK_FUNCTION_EXISTS( sqrt HAVE_SQRT )
CHECK_FUNCTION_EXISTS( stat HAVE_STAT )
CHECK_FUNCTION_EXISTS( strcasecmp HAVE_STRCASECMP )
CHECK_FUNCTION_EXISTS( _stricmp HAVE__STRICMP )
CHECK_FUNCTION_EXISTS( strchr HAVE_STRCHR )
CHECK_FUNCTION_EXISTS( strcspn HAVE_STRCSPN )
CHECK_FUNCTION_EXISTS( strdup HAVE_STRDUP )
CHECK_FUNCTION_EXISTS( strerror HAVE_STRERROR )
CHECK_FUNCTION_EXISTS( strerror_r HAVE_STRERROR_R )
CHECK_FUNCTION_EXISTS( strlcat HAVE_STRLCAT )
CHECK_SYMBOL_EXISTS( strlcpy "string.h;strings.h" HAVE_DECL_STRLCPY )
CHECK_FUNCTION_EXISTS( strlcpy HAVE_STRLCPY )
#SET( HAVE_DECL_STRLCPY ${HAVE_STRLCPY} )
CHECK_FUNCTION_EXISTS( strncasecmp HAVE_STRNCASECMP )
CHECK_FUNCTION_EXISTS( _strnicmp HAVE__STRNICMP )
CHECK_FUNCTION_EXISTS( strpbrk HAVE_STRPBRK )
CHECK_FUNCTION_EXISTS( strrchr HAVE_STRRCHR )
CHECK_FUNCTION_EXISTS( strspn HAVE_STRSPN )
CHECK_FUNCTION_EXISTS( strstr HAVE_STRSTR )
CHECK_FUNCTION_EXISTS( strtol HAVE_STRTOL )
CHECK_FUNCTION_EXISTS( symlink HAVE_SYMLINK )
CHECK_FUNCTION_EXISTS( sysconf HAVE_SYSCONF )
CHECK_FUNCTION_EXISTS( telldir HAVE_TELLDIR )
CHECK_FUNCTION_EXISTS( tempnam HAVE_TEMPNAM )
CHECK_FUNCTION_EXISTS( times HAVE_TIMES )
CHECK_FUNCTION_EXISTS( usleep HAVE_USLEEP )
CHECK_FUNCTION_EXISTS( vfork HAVE_VFORK )
IF( HAVE_VFORK )
	SET( HAVE_WORKING_VFORK 1 )
ENDIF( HAVE_VFORK )
CHECK_FUNCTION_EXISTS( vprintf HAVE_VPRINTF )
IF( NOT HAVE_VPRINTF )
	CHECK_FUNCTION_EXISTS(_doprnt HAVE_DOPRNT )
ENDIF( NOT HAVE_VPRINTF )

CHECK_SYMBOL_EXISTS( vsnprintf stdio.h HAVE_DECL_VSNPRINTF )
CHECK_FUNCTION_EXISTS( vsnprintf HAVE_VSNPRINTF )
CHECK_FUNCTION_EXISTS( vsprintf HAVE_VSPRINTF )
CHECK_FUNCTION_EXISTS( waitpid HAVE_WAITPID )
CHECK_FUNCTION_EXISTS( _exit HAVE__EXIT )
CHECK_FUNCTION_EXISTS( _NSGetExecutablePath HAVE__NSGETEXECUTABLEPATH )
CHECK_FUNCTION_EXISTS( _pclose HAVE__PCLOSE )
CHECK_FUNCTION_EXISTS( _popen HAVE__POPEN )
CHECK_FUNCTION_EXISTS( _wfopen HAVE__WFOPEN )
CHECK_FUNCTION_EXISTS( _wstat HAVE__WSTAT )

SET( CMAKE_REQUIRED_INCLUDES )
SET( CMAKE_REQUIRED_LIBRARIES )

SET ( CMAKE_REQUIRED_LIBRARIES rt )
CHECK_FUNCTION_EXISTS( clock_gettime HAVE_CLOCK_GETTIME )
SET ( CMAKE_REQUIRED_LIBRARIES )

CHECK_SYMBOL_EXISTS( error_t errno.h HAVE_ERROR_T )
CHECK_SYMBOL_EXISTS( fseeko stdio.h HAVE_FSEEKO )
CHECK_INCLUDE_FILE( dirent.h HAVE_DIRENT_H )
CHECK_INCLUDE_FILE( ndir.h HAVE_NDIR_H )
CHECK_INCLUDE_FILE( sys/dir.h HAVE_SYS_DIR_H )
CHECK_INCLUDE_FILE( sys/ndir.h HAVE_SYS_NDIR_H )
CHECK_SYMBOL_EXISTS( DIR dirent.h HAVE_DIR_IN_DIRENT_H )
IF( NOT HAVE_DIR_IN_DIRENT_H )
	CHECK_SYMBOL_EXISTS( DIR ndir.h HAVE_DIR_IN_NDIR_H )
	IF( NOT HAVE_DIR_IN_NDIR_H )
		CHECK_SYMBOL_EXISTS( DIR sys/dir.h HAVE_DIR_IN_SYS_DIR_H )
		IF( NOT HAVE_DIR_IN_SYS_DIR_H )
			CHECK_SYMBOL_EXISTS( DIR sys/ndir.h HAVE_DIR_IN_SYS_NDIR_H )
		ENDIF( NOT HAVE_DIR_IN_SYS_DIR_H )
	ENDIF( NOT HAVE_DIR_IN_NDIR_H )
ENDIF( NOT HAVE_DIR_IN_DIRENT_H )
CHECK_SYMBOL_EXISTS( CLOCK_REALTIME time.h HAVE_CLOCK_REALTIME )
CHECK_SYMBOL_EXISTS( bool stdlib.h HAVE_BOOL )
CHECK_SYMBOL_EXISTS( _Bool stdbool.h HAVE__BOOL )

CHECK_LIBRARY_EXISTS( dl dlopen "" HAVE_LIBDL )
CHECK_LIBRARY_EXISTS( gcov __gcov_init "" HAVE_LIBGCOV )

CHECK_TYPE_SIZE( off_t SIZEOF_OFF_T )
IF( NOT SIZEOF_OFF_T )
	SET( off_t "long int" )
ENDIF( NOT SIZEOF_OFF_T )
CHECK_TYPE_SIZE( "signed int" SIZEOF_SIGNED_INT )
CHECK_TYPE_SIZE( "signed long" SIZEOF_SIGNED_LONG )
CHECK_TYPE_SIZE( "signed long long" SIZEOF_SIGNED_LONG_LONG )
CHECK_TYPE_SIZE( "signed short" SIZEOF_SIGNED_SHORT )
CHECK_TYPE_SIZE( size_t SIZEOF_SIZE_T )
IF( NOT HAVE_SIZEOF_SIZE_T )
	SET( size_t "unsigned int" )
ENDIF( NOT HAVE_SIZEOF_SIZE_T )
CHECK_TYPE_SIZE( "unsigned int" SIZEOF_UNSIGNED_INT )
CHECK_TYPE_SIZE( "unsigned int*" SIZEOF_UNSIGNED_INTP )
CHECK_TYPE_SIZE( "unsigned long" SIZEOF_UNSIGNED_LONG )
CHECK_TYPE_SIZE( "unsigned long long" SIZEOF_UNSIGNED_LONG_LONG )
CHECK_TYPE_SIZE( "unsigned short" SIZEOF_UNSIGNED_SHORT )
CHECK_TYPE_SIZE( pid_t SIZEOF_PID_T )
IF( NOT HAVE_SIZEOF_PID_T )
	SET( pid_t int )
ENDIF( NOT HAVE_SIZEOF_PID_T )
CHECK_TYPE_SIZE( mode_t SIZEOF_MODE_T )
IF( NOT HAVE_SIZEOF_MODE_T )
	SET( mode_t int )
ENDIF( NOT HAVE_SIZEOF_MODE_T )
CHECK_TYPE_SIZE( ssize_t SIZEOF_SSIZE_T )
IF( NOT HAVE_SIZEOF_SSIZE_T )
	IF( WIN32 )
		SET( ssize_t long )
	ELSE( WIN32 )
		SET( ssize_t int )
	ENDIF( WIN32 )
ENDIF( NOT HAVE_SIZEOF_SSIZE_T )
CHECK_TYPE_SIZE( "long double" SIZEOF_LONG_DOUBLE )
CHECK_TYPE_SIZE( double SIZEOF_DOUBLE )
IF( ${SIZEOF_LONG_DOUBLE} GREATER ${SIZEOF_DOUBLE} )
	SET( HAVE_LONG_DOUBLE_WIDER 1 )
ENDIF( ${SIZEOF_LONG_DOUBLE} GREATER ${SIZEOF_DOUBLE} )

IF( HAVE_SYS_TIME_H )
	CHECK_INCLUDE_FILES( "sys/time.h;time.h" TIME_WITH_SYS_TIME )
ENDIF( HAVE_SYS_TIME_H )

CHECK_SYMBOL_EXISTS( "struct tm" sys/time.h TM_IN_SYS_TIME )

SET( HAVE_PTHREADS ${CMAKE_USE_PTHREADS_INIT} )

IF( HAVE_ARGZ_NEXT )
	SET( HAVE_WORKING_ARGZ 1 )
ENDIF( HAVE_ARGZ_NEXT )

CHECK_INCLUDE_FILES( "dlfcn.h;stdint.h;stddef.h;inttypes.h;stdlib.h;strings.h;string.h;float.h" StandardHeadersExist )
IF( StandardHeadersExist )
        CHECK_SYMBOL_EXISTS( memchr string.h memchrExists )
        IF( memchrExists )
                CHECK_SYMBOL_EXISTS( free stdlib.h STDC_HEADERS )
        ENDIF( memchrExists )
ENDIF( StandardHeadersExist )

IF( IMAGEMAGICK_WITH_BZip2 )
	SET( BZLIB_DELEGATE 1 )
ENDIF( IMAGEMAGICK_WITH_BZip2 )
IF( IMAGEMAGICK_WITH_JPEG )
	SET( JPEG_DELEGATE 1 )
ENDIF( IMAGEMAGICK_WITH_JPEG )
IF( IMAGEMAGICK_WITH_PNG )
	SET( PNG_DELEGATE 1 )
ENDIF( IMAGEMAGICK_WITH_PNG )
IF( IMAGEMAGICK_WITH_TIFF )
	SET( TIFF_DELEGATE 1 )
ENDIF( IMAGEMAGICK_WITH_TIFF )
IF( IMAGEMAGICK_WITH_ZLIB )
	SET( ZLIB_DELEGATE 1 )
ENDIF( IMAGEMAGICK_WITH_ZLIB )

# Restrict testing
IF( UNIX )
	CHECK_C_SOURCE_COMPILES("
	/* */

	int main()
	{
		int *restrict pointer;

		return 0;
	}
	" RESTRICT_WORKED )
	IF( NOT RESTRICT_WORKED )

		CHECK_C_SOURCE_COMPILES("
		/* */
		
		int main()
		{
			int *__restrict pointer;
		
			return 0;
		}
		" __RESTRICT_WORKED )
		IF( __RESTRICT_WORKED )
			SET( restrict __restrict )
		ELSE( __RESTRICT_WORKED )
		
			CHECK_C_SOURCE_COMPILES("
			/* */
			
			int main()
			{
				int *__restrict__ pointer;
			
				return 0;
			}
			" __RESTRICT___WORKED )
			IF( __RESTRICT___WORKED )
				SET( restrict __restrict__ )
			ELSE( __RESTRICT___WORKED )
				SET( restrict " " )
			ENDIF( __RESTRICT___WORKED )
		ENDIF( __RESTRICT_WORKED )
	ENDIF( NOT RESTRICT_WORKED )
ELSE( UNIX )
	SET( restrict " " )
ENDIF( UNIX )


