file(GLOB CODERS_SRCS ../coders/*.c)

set(CODERS_DEPENDENT_LIBRARIES )
if(NOT IMAGEMAGICK_WITH_DPS )
	list(REMOVE_ITEM CODERS_SRCS "${CMAKE_CURRENT_SOURCE_DIR}/../coders/dps.c" )
endif()
if(NOT IMAGEMAGICK_WITH_DJVU )
	list(REMOVE_ITEM CODERS_SRCS "${CMAKE_CURRENT_SOURCE_DIR}/../coders/djvu.c" )
endif()
if(NOT IMAGEMAGICK_WITH_OPENEXR )
	list(REMOVE_ITEM CODERS_SRCS "${CMAKE_CURRENT_SOURCE_DIR}/../coders/exr.c" )
endif()
if(NOT IMAGEMAGICK_WITH_FLASHPIX )
	list(REMOVE_ITEM CODERS_SRCS "${CMAKE_CURRENT_SOURCE_DIR}/../coders/fpx.c" )
endif()
if(NOT IMAGEMAGICK_WITH_JBIG )
	list(REMOVE_ITEM CODERS_SRCS "${CMAKE_CURRENT_SOURCE_DIR}/../coders/jbig.c" )
endif()
if(NOT IMAGEMAGICK_WITH_JP2 )
	list(REMOVE_ITEM CODERS_SRCS "${CMAKE_CURRENT_SOURCE_DIR}/../coders/jp2.c" )
endif()
if(IMAGEMAGICK_WITH_PNG )
	set(PNG_NAMES libpng12_static libpng14_static libpng15_static )
	find_package(PNG ${PNG_VERSION} REQUIRED)
	list(APPEND CODERS_DEPENDENT_LIBRARIES png)
        if(APPLE)
                if(CMAKE_SYSTEM_VERSION VERSION_GREATER 13.4.0)
                        set_source_files_properties("${CMAKE_CURRENT_SOURCE_DIR}/../coders/png.c" PROPERTIES COMPILE_FLAGS -DFARDATA="")
                endif()
        endif()
else()
	list(REMOVE_ITEM CODERS_SRCS "${CMAKE_CURRENT_SOURCE_DIR}/../coders/png.c" )
endif()
if(IMAGEMAGICK_WITH_TIFF)
	find_package(TIFF ${TIFF_VERSION} REQUIRED)
	list(APPEND CODERS_DEPENDENT_LIBRARIES tiff)
else()
    list(REMOVE_ITEM CODERS_SRCS "${CMAKE_CURRENT_SOURCE_DIR}/../coders/ept.c" "${CMAKE_CURRENT_SOURCE_DIR}/../coders/tiff.c" )
endif()
if(NOT IMAGEMAGICK_WITH_WINGDI32 )
	list(REMOVE_ITEM CODERS_SRCS "${CMAKE_CURRENT_SOURCE_DIR}/../coders/clipboard.c" "${CMAKE_CURRENT_SOURCE_DIR}/../coders/emf.c" )
endif(NOT IMAGEMAGICK_WITH_WINGDI32 )
if(NOT IMAGEMAGICK_WITH_WMF )
	list(REMOVE_ITEM CODERS_SRCS "${CMAKE_CURRENT_SOURCE_DIR}/../coders/wmf.c" )
endif(NOT IMAGEMAGICK_WITH_WMF )
if(NOT IMAGEMAGICK_WITH_X11 )
	list(REMOVE_ITEM CODERS_SRCS "${CMAKE_CURRENT_SOURCE_DIR}/../coders/x.c" "${CMAKE_CURRENT_SOURCE_DIR}/../coders/xwd.c" )
endif(NOT IMAGEMAGICK_WITH_X11 )
# Place this last by design, trying to manipulate include header order.  Will not work if a system png or tiff is desired
# and a local jpeg.  Currently we use the system jpeg and local png and tiff by default.
if(NOT IMAGEMAGICK_WITH_JPEG)
	LIST(REMOVE_ITEM CODERS_SRCS "${CMAKE_CURRENT_SOURCE_DIR}/../coders/jpeg.c" )
else()
	find_package(JPEG ${JPEG_VERSION} REQUIRED)
	list(APPEND CODERS_DEPENDENT_LIBRARIES jpeg)
endif()

